### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by ohsupertramp** [Gransi/oekofen-pellematic#1]
Hi, 
first, thank you for your code !
ad sorry for my english

I have a problem to connect with my ökofen boiler.

in def getDataFromSystem(url, items):
i have
req=  <Response [200]>
cookie=  <RequestsCookieJar[<Cookie pksession=84055 for x.x.x.x/>]>
Exception as e =  Exceeded 30 redirects.

or
req=  <Response [200]>
cookie=  <RequestsCookieJar[<Cookie pksession=84055 for x.x.x.x/>]>
Exception as e =  ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

and I don't find the problem.

My oekofen boiler is Ökofen pellematic condens with Touch V2.05 18052015 interface
do you have the same interface? 

thank you for the response

**Comment by Gransi** [comment]
Hi ohsupertramp,

I have the version V02.00c.

It looks like, you get no cookies from the login page. 
This is my output from the script.
```
<Response [200]>
<RequestsCookieJar[<Cookie pksession=74548 for 192.XXX.XXX.XXX/>]>
```

Did you run the script with a cron job?
I have noticed that my touch controller is not stable and sometimes the login fails. Currently I work on a new solution with a python thread, which logs in only one time and retrieves the data in a defined time period.

Can you start the network monitor on your browser?

Firefox: https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor
Chrome: https://developers.google.com/web/tools/chrome-devtools/network-performance/

The network monitor shows all the traffic to the touch web interface.
![oekofenlogin](https://user-images.githubusercontent.com/33392356/36810494-24c5256a-1ccb-11e8-8146-625b2d6cf4e6.JPG)

In my system the first entry contains the login parameters, cookies and the response.
